// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrovaBackend.Data;

#nullable disable

namespace TrovaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722110114_VerifyNoOp")]
    partial class VerifyNoOp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrovaBackend.Models.BankConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AvailableBalanceAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageMonthlyCashflowChangePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfCurrentDebts")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfDelinquentDebts")
                        .HasColumnType("integer");

                    b.Property<decimal>("RemainingDebtCapacityJod")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BankConnections");
                });

            modelBuilder.Entity("TrovaBackend.Models.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BidAmountJod")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "ContractorId")
                        .IsUnique();

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("TrovaBackend.Models.CapabilityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgRating")
                        .HasColumnType("double precision");

                    b.Property<string>("CashflowTrendsDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CashflowTrendsScore")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyAssetsValueDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyAssetsValueScore")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentProjects")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentWorkloadDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentWorkloadScore")
                        .HasColumnType("integer");

                    b.Property<string>("DebtCapacityDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DebtCapacityScore")
                        .HasColumnType("integer");

                    b.Property<string>("DelinquentDebtsDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DelinquentDebtsScore")
                        .HasColumnType("integer");

                    b.Property<int>("FailedProjects")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumberOfCurrentDebtsDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfCurrentDebtsScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentHistoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentHistoryScore")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectDeliveryHistoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectDeliveryHistoryScore")
                        .HasColumnType("integer");

                    b.Property<string>("TierLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalProjects")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CapabilityScores");
                });

            modelBuilder.Entity("TrovaBackend.Models.CompanyDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualRevenueJod")
                        .HasColumnType("numeric");

                    b.Property<string>("BusinessLicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassificationLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractorClassificationGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryOfRegistration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalCompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LegalStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisteredAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Sectors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TaxVatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("YearOfEstablishment")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CompanyDetails");
                });

            modelBuilder.Entity("TrovaBackend.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AwardedBidId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BidSubmissionDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ContractValueJod")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuaranteeTypeRequired")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Milestones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinimumClassification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumRequiredScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimelineText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TrovaBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerificationCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityVerificationMethod")
                        .HasColumnType("text");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIdentityVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
